language: node_js
node_js:
  - "4.2.3"

after_success:
  - npm run cover-publish
addons:
  code_climate:
    repo_token:
      # # get your token from https://codeclimate.com/github/benjamine/mongo-listener
      # gem install travis
      # travis encrypt <projecttoken>
      secure: "project's encrypted token"
